# Generated by Django 3.2.5 on 2021-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
