version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./cmc_project:/cmc_project
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A cmc_project beat -l info
    command: celery -A cmc_project worker -l info
    volumes:
        - ./cmc_project:/cmc_project